# Gestion des sons placettes Asellia pour TADARIDA

## Première cellule à exécuter pour paramétrer Python
```{r setup, include=FALSE}
# Pour utiliser Python :
library(reticulate)
library(beepr)
source("variables_perso.R")
# Renseigner Python selon l’env anaconda choisi :
use_python(python)
use_condaenv("Gestion_Sons")
setwd(dossier)
```

## Appel des bibliothèques nécessaires
```{python}
import os # pour la gestion des fichiers
import sys # idem
from pathlib import Path # accès aux dossiers
import psycopg2 as pg # accès à la base de données
import time # gestion formats date/heure
import datetime
from id_bdd import USER, PASSWORD, HOST, PORT, DB_NAME, HOME # imports param conn.
# Contenu de idd_bdd.py à la racine du dossier :
    # DB_NAME = 'nom_bdd'
    # USER = 'nom_utilisateur'
    # PASSWORD = 'mot_de_passe'
    # HOST = 'adresse_ip'
    # PORT = 5432
import pandas as pd # Faire des dataframes
import contextlib # Pour appeler la bdd sans heurts
import csv # Pour le format csv
import shutil as su # Autre outil de gestion des fichiers
import numpy as np # Tableaux de données pour fonctions bdd
import subprocess # pour appeler des scripts externes (shell)
from fonctions_asellia import get_placette_count, get_ligne, updateVigie, updatePoint, updateVigieId, updateParticipationId, get_prefix, get_placette, getSiteParti, nettoyageDossier

```

# Petite boite à outils pour le traitement des fichiers sons vigie-chiro
Préparation des dossiers :
```{python}
# Le dossier de travail et celui ou se trouve le script python
os.chdir('/home/asellia_pc_chiro/Bureau/GESTION_SONS/01_SONS_A_TRAITER')

# Modifier rootdir si a_classer, a_nommer, a_convertir et a_compresser ne sont
# pas au même endroit que le script

#------------ Définition des dossiers de traitement des fichiers -------------#
rootdir = os.getcwd()
a_classer = os.path.join(rootdir, '01_a_classer')
#a_prefixer = os.path.join(rootdir, 'wac_sm2')
a_nommer = os.path.join(rootdir, '02_a_nommer')
#a_nommer_vinc = os.path.join(rootdir, 'a_nommer_vinc')
a_convertir = os.path.join(rootdir, '03_a_convertir')
#a_convertir_vinc = os.path.join(rootdir, 'a_convertir_vinc')
a_compresser = os.path.join(rootdir, '04_a_compresser')
a_envoyer = os.path.join(rootdir, '05_a_envoyer')
stock = os.path.join(rootdir, 'stock')
```

### Évaluation des fichiers .wav et renommage si Passive Recorder
```{python}
# Scanne le dossier a_classer pour des fichiers PR et les renomme au format :
    # PR01_20230415_195512.wav
for subdir, dirs, files in os.walk(a_classer):
    for file in files:
        # On ne traite que les fichiers wav
        if file.split('.')[-1] == 'wav':
            nom = file.split('.')[0]
            test_boitier = nom.split(' ')
            #Pour distinguer du Swift qui commence par une date à 10 caractères :
            if len(test_boitier) > 1 and len(test_boitier[0]) == 4:
            # on est dans un boitier PR
            ## donc il faut renommer
                boite = test_boitier[0]
                codeBoite_date = test_boitier[1]
                nv_nom = boite + '_' + codeBoite_date.split('_')[1] + '_' + codeBoite_date.split('_')[2] + '.wav'
                # Renommage dans le même dossier
                os.rename(f"{subdir}/{file}", f"{subdir}/{nv_nom}")
# Suppression des variables désormais inutiles pour éviter les erreurs
del nom, test_boitier, boite, nv_nom, subdir, dirs, files, file
```

### Évaluation des fichiers .wav et renommage si Swift
```{python}
# Même principe que la cellule précédente, les critères varient
for subdir, dirs, files in os.walk(a_classer):
    for file in files:
        print(file)
        if file.split('.')[-1] == 'wav':
            nom = file.split('.')[0]
            test_boitier = nom.split(' ')
            if len(test_boitier) > 1 and len(test_boitier[0]) == 10:
            # on est dans un boitier swift
            # donc il faut renommer
                boite = 'SW5'
                jour = test_boitier[0].replace('-', '')
                heure = test_boitier[1].replace('-', '')
                nv_nom = boite + '_' + jour + '_' + heure + '.wav'
                print(nv_nom)
                os.rename(f"{subdir}/{file}", f"{subdir}/{nv_nom}")
            elif len(test_boitier) > 1:
                boite = test_boitier[0]
                jour = test_boitier[1].replace('-', '')
                heure = test_boitier[2].replace('-', '')
                nv_nom = boite + '_' + jour + '_' + heure + '.wav'
                print(nv_nom)
                os.rename(f"{subdir}/{file}", f"{subdir}/{nv_nom}")
del subdir, dirs, files, file, nom, test_boitier, boite, jour, nv_nom, heure
```

### Renommage des SM2 sans prefixe
```{python}
# print(a_prefixer)
# numBoitier = 'SM2_' # à modifier selon le boitier à renommer
# for subdir, dirs, files in os.walk(a_prefixer):
    # for file in files:
        # if file.split('.')[-1] == 'wac':
            # nom = file.split('.')[0]
            # nv_nom = numBoitier + nom + '.wac'
            # #nv_nom =  nom[4:] + '.wac'
            # os.rename(f"{subdir}/{file}", f"{subdir}/{nv_nom}")

```

### Déplacer les fichiers dans le bon dossier par boitier puis par date
```{python classement des fichiers}
for subdir, dirs, files in os.walk(a_classer):
    for file in files:
        print(file)
        if file.split('.')[-1] in ('wac', 'wav') and len(file) > 5:
            nom = file.split('.')[0]
            boitier = nom.split('_')[0]
            date = nom.split('_')[1]
            heure = int(nom.split('_')[2][:2])
            path_boitier = os.path.join(a_nommer, boitier)
            exists_boitier = os.path.exists(path_boitier)
# exists_wac = os.path.exists(f"{boitier}/WAC")
            if not exists_boitier:
                os.makedirs(f"{path_boitier}")
            if heure > 11 and heure < 24:
                exists_date = os.path.exists(f"{path_boitier}/{date}")
                if not exists_date:
                    os.makedirs(f"{path_boitier}/{date}")
                    os.makedirs(f"{path_boitier}/{date}/WAC")
                    os.makedirs(f"{path_boitier}/{date}/WAV")
                    
                if len(file.split('_')[-1]) == 7:
                    os.rename(f"{subdir}/{file}", f"{path_boitier}/{date}/WAV/{file}")
                else: 
                    os.rename(f"{subdir}/{file}", f"{path_boitier}/{date}/WAC/{file}")
            else:
                date = pd.to_datetime(date, format = '%Y%m%d') # Transformation dans un format date
                date = date - pd.Timedelta(days = 1) # Calcul de la veille
                date = str(date.strftime('%Y%m%d')) # Retour en format texte
                exists_date = os.path.exists(f"{path_boitier}/{date}/WAC")
                # si le dossier n’existe pas on le crée :
                if not exists_date:
                    os.makedirs(f"{path_boitier}/{date}")
                    os.makedirs(f"{path_boitier}/{date}/WAC")
                    os.makedirs(f"{path_boitier}/{date}/WAV")

                if len(file.split('_')[-1]) == 7:
                    os.rename(f"{subdir}/{file}", f"{path_boitier}/{date}/WAV/{file}")
                else:
                    os.rename(f"{subdir}/{file}", f"{path_boitier}/{date}/WAC/{file}")
r.beep(sound = 1)
```

### Vérification des placettes + nuits boitiers
```{python}
# Création du tableau vide pour les placettes à renommer
nuits_boitiers = pd.DataFrame(columns = ['boitier', 'date', 'date_int', 'heure_deb', 'heure_fin','duree_nuit', 'code_vigie', 'nombre_de_nuits', 'nb_placettes'])

# On parcourt le dossier 'a_nommer'
for subdir, dirs, files in os.walk(a_nommer):

    if subdir.split(os.sep)[-1] == 'WAC':

        # On récupère le nom de boitier :
        boitier = subdir.split(os.sep)[-3]
        print(boitier)
        # # La date :
        date = pd.to_datetime(subdir.split(os.sep)[-2], format = '%Y%m%d').strftime('%Y-%m-%d')
        date_int = subdir.split(os.sep)[-2]
        dates_heures = []
        # # Pour chaque date :
        for file in files:
            # Formatage datetime :
            # modif split('_')[1] et  [2] en -2 et -1
            datef = file.split('.')[0].split('_')[-2]
            heuref = file.split('.')[0].split('_')[-1]
            date_heure = datef + '_' + heuref
            dates_heures.append(pd.to_datetime(date_heure, format = '%Y%m%d_%H%M%S'))
        # Récupération de l’heure de premier/dernier enregistrement :
        heure_deb = min(dates_heures).strftime('%H:%M:%S')
        heure_fin = max(dates_heures).strftime('%H:%M:%S')
        ecart = max(dates_heures) - min(dates_heures)
        print(ecart)
        if ecart < datetime.timedelta(hours=8):
            print(boitier, date)
            print('nuit courte')

        # Remplissage du tableau
        nuits_boitiers = pd.concat([nuits_boitiers, pd.DataFrame.from_records([{'boitier' : boitier, 'date' : date, 'date_int': int(date_int), 'heure_deb' : heure_deb, 'heure_fin' : heure_fin, 'duree_nuit' : ecart}])], ignore_index=True)

# Mise à jour du tableau avec le nombre de nuits par boitier (1 si ok):
with contextlib.ExitStack() as ctx:
    connection = ctx.enter_context(pg.connect(f"host={HOST} dbname={DB_NAME} user={USER} password={PASSWORD} port={PORT}"))
    cursor = ctx.enter_context(connection.cursor())
    for _, row in nuits_boitiers.iterrows():
        rang = dict(row)
        total = get_placette_count(cursor, rang['boitier'], rang['date'])
        nuits_boitiers.at[_, 'nb_placettes'] = total

        print(row['boitier'], row['date'], total)
    cursor.close()

# Vérif de la valeur dans le tableau et renvoi d’un message pour aller vérifier dans la bdd_placettes s’il y a un pb :
for _, row in nuits_boitiers.iterrows():
    if row['nb_placettes'] != 1:
        print(f'Il y a un problème avec le boitier {row["boitier"]} pour la nuit du {pd.to_datetime(row["date"], format = "%Y-%m-%d").strftime("%d-%m-%Y")}')
    if row['duree_nuit'] < datetime.timedelta(hours = 8):
        print(f'il y a un problème avec le boitier {row["boitier"]} pour la nuit du {pd.to_datetime(row["date"], format = "%Y-%m-%d").strftime("%d-%m-%Y")}, la durée d’enregistrement est de {row["duree_nuit"]}')

```

### Création du csv pour code vigie-chiro
```{python}
now = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
print(now)
with open(f'{a_nommer}/a_coder{now}.csv', 'w', newline= '') as file:
    writer = csv.writer(file)
    fields =  ["FirstName","FamilyName","Email","Affiliation","Country","Site","X","Y","Participation","StartDate","EndDate", "TypeStudy", "MicHeight", "Recorder", "Mic", "GainRecorder", "HPF", "FreqMin", "FreqMax", "TriggerLevel", "MinDur", "MaxDur", "TrigWin", "Pause", "TrigWinMax", "FileSplittingLength", "NoiseFilter", "Comment"]
    writer.writerow(fields)
erreurs = []
# Mise à jour du tableau avec le nombre de nuits par boitier (1 si ok):
with contextlib.ExitStack() as ctx:
    connection = ctx.enter_context(pg.connect(f"host={HOST} dbname={DB_NAME} user={USER} password={PASSWORD} port={PORT}"))
    cursor = ctx.enter_context(connection.cursor())


    for _, row in nuits_boitiers.iterrows():
        rang = dict(row)
        ligne = get_ligne(cursor, rang['boitier'], rang['date']) # la récup du type de boitier se fait dans fonctions_asellia.py/get_ligne
        print(ligne)
        if ligne[5] == None:
            erreurs.append(f'Il y a un problème avec le boitier {row["boitier"]} pour la nuit du {pd.to_datetime(row["date"], format = "%Y-%m-%d").strftime("%d-%m-%Y")}, le nom_point n’est pas attribué. Corrigez ça dans la base de données et relancez la cellule.')

        with open(f'{a_nommer}/a_coder{now}.csv', 'a', newline= '') as file:
            writer = csv.writer(file)
            writer.writerow(ligne)
        print(ligne)
    cursor.close()

# Vérif de la valeur dans le tableau et renvoi d’un message pour aller vérifier dans la bdd_placettes s’il y a un pb :
for _, row in nuits_boitiers.iterrows():
    if row['nb_placettes'] != 1:
        print(f'Il y a un problème avec le boitier {row["boitier"]} pour la nuit du {pd.to_datetime(row["date"], format = "%Y-%m-%d").strftime("%d-%m-%Y")}')
    
for erreur in erreurs:
    print(erreur)
csv_orig = pd.read_csv(f"{a_nommer}/a_coder{now}.csv")
csv2 = csv_orig.drop_duplicates()
csv2.to_csv(f"{a_nommer}/a_coder{now}_ok.csv", sep=';')
exists_csv_ok = os.path.exists(f"{a_nommer}/a_coder{now}_ok.csv")

if exists_csv_ok:
    os.remove(f"{a_nommer}/a_coder{now}.csv")
```

Ici exécuter le script find_points_orig.R Puis Participations.Rmd

### Mise a jour du point vigie chiro dans la bdd placettes
```{python}

if os.path.exists(f'{a_nommer}/NewPoints_ok.csv'):
    newPoints = pd.read_csv(f'{a_nommer}/NewPoints_ok.csv', sep = ";", dtype = {'Carre' : str})


    with contextlib.ExitStack() as ctx:
        connection = ctx.enter_context(pg.connect(f"host={HOST} dbname={DB_NAME} user={USER} password={PASSWORD} port={PORT}"))
        cursor = ctx.enter_context(connection.cursor())
    
        for row in newPoints.itertuples():
            updateVigie(cursor, row.Site, row.Carre)
            updatePoint(cursor, row.Site, row.Point)
    
            updated_rows = cursor.rowcount
            print(updated_rows)
                # Commit the changes to the database
            connection.commit()
        cursor.close()
    os.remove(f'{a_nommer}/NewPoints_ok.csv')

if os.path.exists(f'{a_nommer}/OldPoints_ok.csv'):    
    oldPoints = pd.read_csv(f'{a_nommer}/OldPoints_ok.csv', sep = ";", dtype = {'titre' : str})
    oldPoints[["vigiech", "pointfixe","Carre"]] = oldPoints["titre"].str.split('-', n=3, expand = True)
    print(oldPoints["Carre"])
    with contextlib.ExitStack() as ctx:
        connection = ctx.enter_context(pg.connect(f"host={HOST} dbname={DB_NAME} user={USER} password={PASSWORD} port={PORT}"))
        cursor = ctx.enter_context(connection.cursor())
    
        for row in oldPoints.itertuples():
            updateVigie(cursor, row.Site, row.Carre)
            updatePoint(cursor, row.Site, row.Point)
    
            updated_rows = cursor.rowcount
            print(updated_rows)
                # Commit the changes to the database
            connection.commit()
        cursor.close()
    os.remove(f'{a_nommer}/OldPoints_ok.csv')
r.beep(sound = 1)
```

### Puis mise à jour des Participations : \## Update participation
```{python}

# Mettre ici le nom du csv a_coder_..._created.csv
participations = pd.read_csv(f'{a_nommer}/a_coder20240429_103840_ok_created.csv', sep = ";")

with contextlib.ExitStack() as ctx:
    connection = ctx.enter_context(pg.connect(f"host={HOST} dbname={DB_NAME} user={USER} password={PASSWORD} port={PORT}"))
    cursor = ctx.enter_context(connection.cursor())

    for row in participations.itertuples():
        updateVigieId(cursor, row.idsite, row.Site, row.StartDate) # maj
        updateParticipationId(cursor, row.idparticipation, row.Site,
        row.StartDate)
        updated_rows = cursor.rowcount
        print(updated_rows)
            # Commit the changes to the database
        connection.commit()
    cursor.close()

r.beep(sound = 1)
```

### Renommage (à adapter à la requête sql)
```{python}
# On parcourt le dossier 'a_nommer'
for subdir, dirs, files in os.walk(a_nommer):

    if subdir.split(os.sep)[-1] == 'WAC':
        prefixe = ' '
        # # On récupère le nom de boitier :
        boitier = subdir.split(os.sep)[-3]

        # # La date :
        date = pd.to_datetime(subdir.split(os.sep)[-2], format = '%Y%m%d').strftime('%Y-%m-%d')
        date_int = subdir.split(os.sep)[-2] # vérif util

        path_boitier_conv = os.path.join(a_convertir, boitier)
        exists_boitier_conv = os.path.exists(path_boitier_conv)
        if not exists_boitier_conv:
            os.makedirs(f"{path_boitier_conv}")
        date_path = subdir.split(os.sep)[-2]

        exists_date_conv = os.path.exists(f"{path_boitier_conv}/{date_path}")
        if not exists_date_conv:
            os.makedirs(f"{path_boitier_conv}/{date_path}")

        exists_wac_conv = os.path.exists(f"{path_boitier_conv}/{date_path}/WAC")
        if not exists_wac_conv:
            os.makedirs(f"{path_boitier_conv}/{date_path}/WAC")

        path_rename = f"{path_boitier_conv}/{date_path}/WAC"
        print(path_rename)
        with contextlib.ExitStack() as ctx:
            connection = ctx.enter_context(pg.connect(f"host={HOST} dbname={DB_NAME} user={USER} password={PASSWORD} port={PORT}"))
            cursor = ctx.enter_context(connection.cursor())

            prefixe = get_prefix(cursor, boitier, date)

            cursor.close()
        if prefixe:
            print(len(files))
            for file in files:
                print(file)
                if len(file.split('_')) > 4:
                    nom_complet = file
                else:
                    nom_complet = prefixe + file

                os.rename(os.path.join(subdir, file), os.path.join(path_rename, nom_complet))

        if not prefixe:
            print(len(files))
            print(f"Controlez la placette {boitier} à la date {date}")


    elif subdir.split(os.sep)[-1] == 'WAV':
        prefixe = ' '
        # # On récupère le nom de boitier :
        boitier = subdir.split(os.sep)[-3]

        # # La date :
        date = pd.to_datetime(subdir.split(os.sep)[-2], format = '%Y%m%d').strftime('%Y-%m-%d')
        date_int = subdir.split(os.sep)[-2] # vérif util

        path_boitier_conv = os.path.join(a_convertir, boitier)
        exists_boitier_conv = os.path.exists(path_boitier_conv)
        if not exists_boitier_conv:
            os.makedirs(f"{path_boitier_conv}")
        date_path = subdir.split(os.sep)[-2]

        exists_date_conv = os.path.exists(f"{path_boitier_conv}/{date_path}")
        if not exists_date_conv:
            os.makedirs(f"{path_boitier_conv}/{date_path}")
            os.makedirs(f"{path_boitier_conv}/{date_path}/WAV")

        path_rename = f"{path_boitier_conv}/{date_path}/WAV"
        print(path_rename)
        with contextlib.ExitStack() as ctx:
            connection = ctx.enter_context(pg.connect(f"host={HOST} dbname={DB_NAME} user={USER} password={PASSWORD} port={PORT}"))
            cursor = ctx.enter_context(connection.cursor())

            prefixe = get_prefix(cursor, boitier, date)

            cursor.close()
        if prefixe:
            print(len(files))
            for file in files:
            #     print(file)
                if len(file.split('_')) > 4:
                    nom_complet = file
                else:
                    nom_complet = prefixe + file

                os.rename(os.path.join(subdir, file), os.path.join(path_rename, nom_complet))

        if not prefixe:
            print(len(files))
            print(f"Controlez la placette {boitier} à la date {date}")

nettoyageDossier(a_nommer)
nettoyageDossier(a_nommer)
nettoyageDossier(a_nommer)
r.beep(sound = 1)
```

### Découpage/expansion des fichiers (attention, demandeur en ressources, ne pas faire pour des dizaines de nuits)
```{python}
nettoyageDossier(a_convertir)
nettoyageDossier(a_convertir)
nettoyageDossier(a_convertir)

for subdir, dirs, files in os.walk(a_convertir):
    print(dirs)
# On cherche à convertir le contenu du dossier WAC en fichiers expansés de 5s
    if 'WAC' in dirs and 'WAV' not in dirs:
        os.chdir(subdir)
        boitier = subdir.split(os.sep)[-2]
        print(boitier)
        if 'PR' in boitier:
            print("passive recorder")
            subprocess.run(["pwd"])
            subprocess.run(["tadam.py", "-i", f"{subdir}{os.sep}WAC", "-o", f"{subdir}{os.sep}WAV","-r", "1", "-l", "50", "-v"])
        # Pour les autre on multiplie par 10 ('-r 0.1')
        else:
            print("SM ou SW5")
            subprocess.run(["pwd"])
            subprocess.run(["tadam.py", "-i", f"{subdir}{os.sep}WAC", "-o", f"{subdir}{os.sep}WAV", "-r", "0.1", "-l", "50", "-v"])
r.beep(sound = 1)
```

## Vérification
Plus utile sauf en cas de doute sur tadam.py, mais a tjs fonctionné jusque-là.
```{python}

# def get_placette(cursor, boitier, date):
    # query = """select etude, "lieu-dit", nom_point, passage
        # from bd_sons.bdd_placettes_2023 t1
        # where num_sm2 = %s
        # and %s - to_char("date", \'YYYYMMdd\')::integer between 0 and (nombre_de_nuits - 1);"""
    # cursor.execute(query, [boitier, date])
    # results = cursor.fetchone()
    # return results if results else ''

# import numpy as np
# for subdir, dirs, files in os.walk(a_convertir):
    # liste_wac = []
    # liste_wav = []
    # if subdir.split(os.sep)[-1] ==  'WAC':
        # boitier = subdir.split(os.sep)[-3]
        # date_int = subdir.split(os.sep)[-2]
        # dir_nuit = os.path.join(subdir[:-3], 'WAV')
        # for file in files:
            # # remplissage de la liste des fichiers dans 'WAV'
            # liste_wac.append(file[:-4])
        # # Penser à nommer subdir différemment dans cette boucle pour éviter
        # # la confusion avec celui de la boucle mère
        # for dirn, dirs, files in os.walk(dir_nuit):
            # for file in files:
                # if len(file.split('_')[-1]) == 7: # num fichier inf à 999
                    # # remplissage de la liste des fichiers dans 'WAC'
                    # liste_wav.append(file[:-8])
                # if len(file.split('_')[-1]) == 8: # num fichier sup à 999
                    # # remplissage de la liste des fichiers dans 'WAC'
                    # liste_wav.append(file[:-9])

        # liste_wavnp = np.array(liste_wav)
        # liste_wavnp = np.unique(liste_wavnp)
        # liste_wav = liste_wavnp.tolist()
        # res = []
        # print(subdir)
        # # vérification de l’expansion des fichiers :
        # # on compare les deux listes
        # print(liste_wav)
        # if len(liste_wac) != len(liste_wav):
            # res = [x for x in liste_wav + liste_wac if x not in liste_wav or x not in liste_wac]
            # print(len(res))
            # print(len(liste_wac), len(liste_wav))
        # else:
            # print("Tous les fichiers ont bien été expansés")
            # with contextlib.ExitStack() as ctx:
                # connection = ctx.enter_context(pg.connect(f"host={HOST} dbname={DB_NAME} user={USER} password={PASSWORD} port={PORT}"))
                # cursor = ctx.enter_context(connection.cursor())

                # placette = get_placette(cursor, boitier, date_int)

                # cursor.close()
            # if len(placette) == 4:
                # print(placette[0], placette[1])
                # passage = 'Pass' + str(placette[3])
                # nomPoint = placette[2] + '_' + placette[1]
                # print(subdir.split(os.sep)[-1])
                # # shutil.move permet de déplacer des dossiers/fichiers
                # su.move(subdir, os.path.join(a_compresser, placette[0], passage, nomPoint, date_int, 'WAC') )
                # su.move(dir_nuit, os.path.join(a_compresser, placette[0], passage, nomPoint, date_int, 'WAV') )
    # elif subdir.split(os.sep)[-3] in ('SM1', 'SM2', 'SM3', 'SM4') :
        # boitier = subdir.split(os.sep)[-3]
        # date_int = subdir.split(os.sep)[-2]
        # with contextlib.ExitStack() as ctx:
                # connection = ctx.enter_context(pg.connect(f"host={HOST} dbname={DB_NAME} user={USER} password={PASSWORD} port={PORT}"))
                # cursor = ctx.enter_context(connection.cursor())

                # placette = get_placette(cursor, boitier, date_int)

                # cursor.close()
        # if len(placette) == 4:
            # print(placette[0], placette[1])
            # passage = 'Pass' + str(placette[3])
            # print(subdir.split(os.sep)[-1])
            # nomPoint = placette[2] + '_' + placette[1]
            # su.copytree(subdir, os.path.join(a_compresser, placette[0], passage, nomPoint, 'WAC') )
            # su.copytree(dir_nuit, os.path.join(a_compresser,
            # placette[0],passage, nomPoint, 'WAV'))
```

### Rangement dans a_compresser
```{python}
for subdir, dirs, files in os.walk(a_convertir):
    if subdir.split(os.sep)[-1] ==  'WAC':
        boitier = subdir.split(os.sep)[-3]
        date_int = subdir.split(os.sep)[-2]
        dir_nuit = os.path.join(subdir[:-3], 'WAV')
        with contextlib.ExitStack() as ctx:
            connection = ctx.enter_context(pg.connect(f"host={HOST} dbname={DB_NAME} user={USER} password={PASSWORD} port={PORT}"))
            cursor = ctx.enter_context(connection.cursor())

            placette = get_placette(cursor, boitier, date_int)

            cursor.close()
            if len(placette) == 4:
                print(placette[0], placette[1])
                passage = 'Pass' + str(placette[3])
                nomPoint = placette[2] + '_' + placette[1]
                print(subdir.split(os.sep)[-1])
                        # shutil.move permet de déplacer des dossiers/fichiers
                su.move(subdir, os.path.join(a_compresser, placette[0], passage, nomPoint, date_int, 'WAC') )

                su.move(dir_nuit, os.path.join(a_compresser, placette[0], passage, nomPoint, date_int, 'WAV') )

            elif subdir.split(os.sep)[-3] in ('SM1', 'SM2', 'SM3', 'SM4') :
                boitier = subdir.split(os.sep)[-3]
                date_int = subdir.split(os.sep)[-2]
                with contextlib.ExitStack() as ctx:
                    connection = ctx.enter_context(pg.connect(f"host={HOST} dbname={DB_NAME} user={USER} password={PASSWORD} port={PORT}"))
                    cursor = ctx.enter_context(connection.cursor())

                    placette = get_placette(cursor, boitier, date_int)

                cursor.close()
            # if len(placette) == 4:
            # print(placette[0], placette[1])
            # passage = 'Pass' + str(placette[3])
            # print(subdir.split(os.sep)[-1])
            # nomPoint = placette[2] + '_' + placette[1]
            # su.copytree(subdir, os.path.join(a_compresser, placette[0], passage, nomPoint, 'WAC') )
            # su.copytree(dir_nuit, os.path.join(a_compresser,placette[0],passage, nomPoint, 'WAV'))

nettoyageDossier(a_convertir)
nettoyageDossier(a_convertir)
nettoyageDossier(a_convertir)

for subdir, dirs, files in os.walk(a_compresser):
    if subdir.split(os.sep)[-1] in ('WAV', 'WAC'):
        if subdir.split(os.sep)[-2].isnumeric():
            chemin = subdir.split(os.sep)
            chemin.pop(-2)
            bon_chemin = os.path.join('/', *chemin)
            dossier_existe = os.path.exists(bon_chemin)
            if not dossier_existe:
                os.makedirs(bon_chemin)
            if len(files)>0:
                print(f"Déplacement depuis {subdir} \n vers {bon_chemin}")
                print("...")
                for file in files:
                    os.rename(f"{subdir}/{file}", f"{bon_chemin}/{file}")
                print("... ok")
nettoyageDossier(a_compresser)
nettoyageDossier(a_compresser)
r.beep(sound = 1)
```

## Zippage

```{python}
def sevenzip(filename, zipname):
    system = subprocess.Popen(["7z", "-v700m", "a", zipname, filename])
    return(system.communicate())

for subdir, dirs, files in os.walk(a_compresser):
    if 'WAV' in dirs:
        os.chdir(subdir)
        for sousdos, dos, fich in os.walk(subdir):
            if sousdos.split(os.sep)[-1] == 'WAV' and len(fich) > 10:
                nom = fich[0].split('_')[0] + '_' + fich[0].split('_')[1] + '_' + fich[0].split('_')[4]
                subprocess.run(["pwd"])
                sevenzip("WAV", f"{a_envoyer}/{nom}.zip")
```

### Préparation des fichiers tar pour envoi

```{python}
path_tar = os.path.join(a_envoyer, 'tar')
exists_tar = os.path.exists(path_tar)

if not exists_tar:
    os.makedirs(f"{path_tar}")

    os.makedirs(stock)

for subdir, dirs, files in os.walk(a_compresser):
    print(subdir)
    if subdir.split(os.sep)[-1] == 'WAV' and len(files)>0:
        placette = files[0].split('_')[1]
        dateint = files[0].split('_')[4]
        date = pd.to_datetime(dateint, format = '%Y%m%d').strftime('%Y-%m-%d')
        print(date)

        print(placette, dateint)
        with contextlib.ExitStack() as ctx:
            connection = ctx.enter_context(pg.connect(f"host={HOST} dbname={DB_NAME} user={USER} password={PASSWORD} port={PORT}"))
            cursor = ctx.enter_context(connection.cursor())

            siteParti = getSiteParti(cursor, placette, date)

            cursor.close()
            if siteParti != '':
                print(siteParti)
                path_site = os.path.join(path_tar, siteParti[0])
                exists_site = os.path.exists(path_site)

                if not exists_site:
                    os.makedirs(f"{path_site}")
                    print(f"création de {path_site}")
                path_parti = os.path.join(path_tar, siteParti[0], siteParti[1])
                exists_parti = os.path.exists(path_parti)

                if not exists_parti:
                    os.makedirs(f"{path_parti}")


                for file in files:
                    print(f"{subdir}/{file} > {a_envoyer}/tar/{siteParti[0]}/{siteParti[1]}/{file}")
                    # os.system(f"cp {subdir}/{file} {a_envoyer}/tar/{siteParti[0]}/{siteParti[1]}/{file}")
                    su.copy(f"{subdir}/{file}", f"{a_envoyer}/tar/{siteParti[0]}/{siteParti[1]}/{file}")
            else:
                print(f"{subdir} sans id parti")
            # os.system(f"copy {subdir}/{file} {a_compresser}/{siteParti[0]}/{siteParti[1]}/{file}")
r.beep(sound = 1)
```
